/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playlist;

import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ACER
 */
public class AddMusik extends javax.swing.JFrame {
    private dbConnection db;
    private String filename = null;
    private byte[] person_image=null;
    private int id_user;
    /**
     * Creates new form AddMusikCard
     */
    
    public AddMusik() {
        initComponents();
        db = new dbConnection();
        ResultSet res = db.selectQuery("SELECT id, nama FROM penyanyi WHERE id_user="+id_user);
        try {
            while (res.next()) {
                int id_penyanyi = res.getInt("id");
                String penyanyi = res.getString("nama");
                ComboBoxPenyanyi.addItem (Integer.toString(id_penyanyi) + "-" + penyanyi);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public AddMusik(int id_user) {
        initComponents();
        db = new dbConnection();
        this.id_user = id_user;
        ResultSet res = db.selectQuery("SELECT id, nama FROM penyanyi WHERE id_user="+id_user);
        try {
            while (res.next()) {
                int id_penyanyi = res.getInt("id");
                String penyanyi = res.getString("nama");
                ComboBoxPenyanyi.addItem (Integer.toString(id_penyanyi) + "-" + penyanyi);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void resetform() {
        FieldJudul.setText("");
        FieldDurasi.setText("");
        ComboBoxPenyanyi.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelJudul = new javax.swing.JLabel();
        LabelPenyanyi = new javax.swing.JLabel();
        LabelDurasi = new javax.swing.JLabel();
        LabelGambar = new javax.swing.JLabel();
        FieldJudul = new javax.swing.JTextField();
        FieldDurasi = new javax.swing.JTextField();
        UploadButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ComboBoxPenyanyi = new javax.swing.JComboBox<>();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(290, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Data");

        LabelJudul.setText("Judul Lagu");

        LabelPenyanyi.setText("Penyanyi");

        LabelDurasi.setText("Durasi Waktu");

        LabelGambar.setText("Gambar");

        UploadButton.setText("Upload");
        UploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadButtonActionPerformed(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ComboBoxPenyanyi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxPenyanyiActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelButton)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelJudul)
                            .addComponent(LabelPenyanyi)
                            .addComponent(LabelDurasi)
                            .addComponent(LabelGambar)
                            .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FieldDurasi)
                            .addComponent(FieldJudul)
                            .addComponent(UploadButton)
                            .addComponent(ComboBoxPenyanyi, 0, 156, Short.MAX_VALUE))))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FieldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelJudul))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelPenyanyi)
                        .addGap(24, 24, 24)
                        .addComponent(LabelDurasi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(ComboBoxPenyanyi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FieldDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGambar)
                    .addComponent(UploadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(CancelButton)
                    .addComponent(BackButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(LabelGambar.getWidth(), LabelGambar.getHeight(), Image.SCALE_SMOOTH));
        LabelGambar.setIcon(imageIcon);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum=fis.read(buf))!=-1;)
            {
                bos.write(buf, 0, readNum);
            }
            person_image=bos.toByteArray();  
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_UploadButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String judul = FieldJudul.getText();
        String penyanyi = ComboBoxPenyanyi.getSelectedItem().toString(); // 1 - Miki Matsubara
        String[] parts = penyanyi.split("-");
        String id_penyanyi = parts[0]; 
        String nama_penyanyi = parts[1]; 
        String durasi = FieldDurasi.getText();
        int id = Integer.parseInt(id_penyanyi);
        
        // Add New Data
        if(!judul.isEmpty() && !nama_penyanyi.isEmpty() && !durasi.isEmpty() && person_image != null)
        {
            String sql = "INSERT INTO musik (judul, id_penyanyi, durasi, gambar, id_user) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pst = null;
            try {
                pst = (PreparedStatement) db.conn.prepareStatement(sql);
            } catch (SQLException ex) {
                Logger.getLogger(AddMusik.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                pst.setString(1, judul);
                pst.setInt(2, id);
                pst.setString(3, durasi);
                pst.setBytes(4, person_image);
                pst.setInt(5, id_user);
                pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(AddMusik.class.getName()).log(Level.SEVERE, null, ex);
            }


            sql = "UPDATE penyanyi SET jumlahLagu=jumlahLagu+1 WHERE id="+id;
            db.updateQuery(sql);

            // Show Information
            System.out.println("Insert Success");
            JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
        }
        else
        {
            System.out.println("Insert Failed");
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan");
        }
        dispose();
        Main mf = new Main(id_user, 1);
        mf.setVisible(true);
    }//GEN-LAST:event_AddButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        resetform();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ComboBoxPenyanyiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxPenyanyiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ComboBoxPenyanyiActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        Main mf = new Main(id_user, 1);
        mf.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPenyanyi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPenyanyi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPenyanyi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPenyanyi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMusik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox<String> ComboBoxPenyanyi;
    private javax.swing.JTextField FieldDurasi;
    private javax.swing.JTextField FieldJudul;
    private javax.swing.JLabel LabelDurasi;
    private javax.swing.JLabel LabelGambar;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelPenyanyi;
    private javax.swing.JButton UploadButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
