/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playlist;

import java.sql.ResultSet;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class Main extends javax.swing.JFrame {
    // Properties
    private dbConnection db;
    private int id;
    private int id_user;
    
    // Atribut untuk Musik Card
    private String judul;
    private int id_penyanyi;
    private String penyanyi;
    private String durasi;
    private byte[] img_musik;
    
    // Atribut untuk Penyanyi Card
    private String nama;
    private int jumlah;
    private String tahun;
    private byte[] img_penyanyi;
    /**
     * Creates new form ListMusik
     */
    public Main() {
        initComponents();
        db = new dbConnection();
        setPanel1();
        setSize(425,438);
    }
    
    public Main(int id_user, int card) {
        initComponents();
        db = new dbConnection();
        this.id_user = id_user;
        if (card == 1) {
            setPanel1(); // Musik
            LabelJudul.setText("Playlist Music");
        }
        else {
            setPanel2(); // Penyanyi
            LabelJudul.setText("List Penyanyi");
        }
        setSize(425,438);
    }
    
    public void setPanel1() {
        mainPanel.removeAll();
        mainPanel.setLayout(new GridLayout(0, 1));
        ResultSet res = db.selectQuery("SELECT * FROM musik WHERE id_user ="+id_user);
        try {
            while (res.next()) {
                this.id = res.getInt("id");
                this.judul = res.getString("judul");
                this.id_penyanyi = res.getInt("id_penyanyi");
                this.durasi = res.getString("durasi");
                this.img_musik = res.getBytes("gambar");
                
                mainPanel.add(new MusikCard(id, judul, id_penyanyi, durasi, img_musik, id_user));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    
    public void setPanel2() {
        mainPanel.removeAll();
        mainPanel.setLayout(new GridLayout(0, 1));
        ResultSet res = db.selectQuery("SELECT * FROM penyanyi WHERE id_user="+id_user);
        try {
            while (res.next()) {
                this.id = res.getInt("id");
                this.nama = res.getString("nama");
                this.jumlah = res.getInt("jumlahLagu");
                this.tahun = res.getString("tahunDebut");
                this.img_penyanyi = res.getBytes("gambar");
                mainPanel.add(new PenyanyiCard(id, nama, jumlah, tahun, img_penyanyi, id_user));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        AddButton = new javax.swing.JButton();
        PenyanyiButton = new javax.swing.JButton();
        MusikButton = new javax.swing.JButton();
        LabelJudul = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainPanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 97, 399, 246);

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton);
        AddButton.setBounds(256, 21, 108, 36);

        PenyanyiButton.setText("List Penyanyi");
        PenyanyiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenyanyiButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PenyanyiButton);
        PenyanyiButton.setBounds(6, 21, 108, 36);

        MusikButton.setText("List Musik");
        MusikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusikButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MusikButton);
        MusikButton.setBounds(136, 21, 108, 36);

        LabelJudul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelJudul.setText("List Penyanyi");
        getContentPane().add(LabelJudul);
        LabelJudul.setBounds(141, 63, 125, 28);

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton);
        LogoutButton.setBounds(6, 355, 108, 36);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\avinash-kumar-Yr146Eua_mM-unsplash.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        if (LabelJudul.getText().equals("Playlist Music")) {
            AddMusik add = new AddMusik(id_user);
            add.setVisible(true);
            setVisible(false);
//            add.setMusikCard();
        }
        else {
            AddPenyanyi add = new AddPenyanyi(id_user);
            add.setVisible(true);
            setVisible(false);
//            add.setPenyanyiCard();
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void PenyanyiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenyanyiButtonActionPerformed
        // TODO add your handling code here:
        setPanel2();
        LabelJudul.setText("List Penyanyi");
    }//GEN-LAST:event_PenyanyiButtonActionPerformed

    private void MusikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusikButtonActionPerformed
        // TODO add your handling code here:
        setPanel1();
        LabelJudul.setText("Playlist Music");
    }//GEN-LAST:event_MusikButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        User logout = new User();
        logout.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton MusikButton;
    private javax.swing.JButton PenyanyiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
