/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package playlist;

import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ACER
 */
public class MusikCard extends javax.swing.JPanel {
    private dbConnection db;
    private int id;
    private byte[] picture;
    private int id_user;
    private int id_penyanyi;
    private String judul;
    private String durasi;
    /**
     * Creates new form MusikCard
     */
    public MusikCard(int id, String judul, int id_penyanyi, String durasi, byte[] image, int id_user) {
        initComponents();
        db = new dbConnection();
        this.id = id;
        this.id_user = id_user;
        this.id_penyanyi = id_penyanyi;
        this.judul = judul;
        this.durasi = durasi;
        jLabelJudul.setText(judul);
        ResultSet res = db.selectQuery("SELECT nama FROM penyanyi WHERE id="+id_penyanyi);
        String penyanyi="";
        try {
            if(res.next()){
                penyanyi = res.getString("nama");
            }
        } catch (SQLException ex) {
            Logger.getLogger(MusikCard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jLabelPenyanyi.setText(penyanyi);
        jLabelDurasi.setText(durasi);
        this.picture = image;
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(100, 96, Image.SCALE_SMOOTH));
        jLabelGambar.setIcon(imageIcon);
        
    }
    
    public void deleteData() {
        // Remove Data from List
        String sql = "DELETE from musik WHERE id="+id;
        db.updateQuery(sql);
        
        sql = "UPDATE penyanyi SET jumlahLagu=jumlahLagu-1 WHERE id="+id_penyanyi;
        db.updateQuery(sql);
        
        // Show Information
        System.out.println("Delete Success");
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        
        Main mainFrame = (Main) getTopLevelAncestor();
        mainFrame.setPanel1();
    }
    
    public void updateData()
    {
        EditMusik form = new EditMusik(id, id_user, id_penyanyi);
        form.setVisible(true);
        Main mainFrame = (Main) getTopLevelAncestor();
        mainFrame.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelGambar = new javax.swing.JLabel();
        jLabelJudul = new javax.swing.JLabel();
        jLabelPenyanyi = new javax.swing.JLabel();
        jLabelDurasi = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jLabelGambar = new javax.swing.JLabel();

        LabelGambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelJudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelJudul.setText("Judul Lagu");

        jLabelPenyanyi.setText("Penyanyi");

        jLabelDurasi.setText("Durasi Waktu");

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jLabelGambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelDurasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPenyanyi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelJudul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UpdateButton)
                        .addGap(33, 33, 33)
                        .addComponent(DeleteButton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelJudul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPenyanyi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDurasi)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateButton)
                            .addComponent(DeleteButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        int isDelete = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapusnya?", "Delete Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (JOptionPane.YES_NO_OPTION == isDelete) 
        {
            deleteData();
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        updateData();
    }//GEN-LAST:event_UpdateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel LabelGambar;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabelDurasi;
    private javax.swing.JLabel jLabelGambar;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JLabel jLabelPenyanyi;
    // End of variables declaration//GEN-END:variables
}
