/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package playlist;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class PenyanyiCard extends javax.swing.JPanel {
    // Properties
    private dbConnection db;
    private byte[] picture;
    private int id;
    private int id_user;
    private String nama;
    private int jumlah;
    private String tahun;
    /**
     * Creates new form ListPenyanyi
     */
    public PenyanyiCard(int id, String nama, int jumlah, String tahun, byte[] image, int id_user) {
        initComponents();
        db = new dbConnection();
        this.id = id;
        this.id_user = id_user;
        this.nama = nama;
        this.jumlah = jumlah;
        this.tahun = tahun;
        LabelNama.setText(nama);
        LabelJmlLagu.setText("Jumlah lagu: " + jumlah);
        LabelTahun.setText("Tahun debut : " + tahun);
        this.picture = image;
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(100, 96, Image.SCALE_SMOOTH));
        LabelGambar.setIcon(imageIcon);
    }
    
    public void deleteData() {
        // Remove Data from List
        String sql = "DELETE from musik WHERE id_penyanyi="+id;
        db.updateQuery(sql);
        sql = "DELETE from penyanyi WHERE id="+id;
        db.updateQuery(sql);
        
        // Show Information
        System.out.println("Delete Success");
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        
        Main mainFrame = (Main) getTopLevelAncestor();
        mainFrame.setPanel2();
    }
    
    public void updateData()
    {
        EditPenyanyi form = new EditPenyanyi(id, id_user);
        form.setVisible(true);
        Main mainFrame = (Main) getTopLevelAncestor();
        mainFrame.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelGambar = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        LabelJmlLagu = new javax.swing.JLabel();
        LabelTahun = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();

        LabelGambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNama.setText("Nama");

        LabelJmlLagu.setText("Jumlah Lagu");

        LabelTahun.setText("Tahun Debut");

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LabelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelJmlLagu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelTahun, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeleteButton)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelNama)
                        .addGap(2, 2, 2)
                        .addComponent(LabelJmlLagu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTahun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateButton)
                            .addComponent(DeleteButton)))
                    .addComponent(LabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        updateData();
    }//GEN-LAST:event_UpdateButtonActionPerformed
    
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        int isDelete = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapusnya?", "Delete Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (JOptionPane.YES_NO_OPTION == isDelete) 
        {
            deleteData();
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel LabelGambar;
    private javax.swing.JLabel LabelJmlLagu;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelTahun;
    private javax.swing.JButton UpdateButton;
    // End of variables declaration//GEN-END:variables

}
