/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playlist;

import java.sql.ResultSet;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ACER
 */
public class User extends javax.swing.JFrame {
    // Properties
    private dbConnection db;
    private int id;
    private String username;
    private String password;
    private boolean user = false;
    /**
     * Creates new form Login
     */
    public User() {
        initComponents();
        db = new dbConnection();
        setSize(332,345);
        RegisterButton.setVisible(false);
//        AlertFailed.setVisible(false);
    }
    
    public void resetform() {
        FieldUsername.setText("");
        FieldPass.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelUsername = new javax.swing.JLabel();
        FieldUsername = new javax.swing.JTextField();
        LabelPass = new javax.swing.JLabel();
        FieldPass = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Akun Saya");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(104, 33, 90, 25);

        LabelUsername.setText("Username :");
        getContentPane().add(LabelUsername);
        LabelUsername.setBounds(20, 80, 70, 16);

        FieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(FieldUsername);
        FieldUsername.setBounds(100, 80, 162, 22);

        LabelPass.setText("Password :");
        getContentPane().add(LabelPass);
        LabelPass.setBounds(20, 130, 70, 16);
        getContentPane().add(FieldPass);
        FieldPass.setBounds(100, 130, 162, 22);

        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginButton.setText("Masuk");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton);
        LoginButton.setBounds(120, 210, 72, 31);

        RegisterButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegisterButton.setText("Daftar");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterButton);
        RegisterButton.setBounds(120, 260, 72, 31);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\avinash-kumar-Yr146Eua_mM-unsplash.jpg")); // NOI18N
        jLabel4.setText("Daftar");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 330, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        ResultSet res = db.selectQuery("SELECT * FROM user");
        try {
            while (res.next()) {
                if(FieldUsername.getText().equals(res.getString("username")) && FieldPass.getText().equals(res.getString("password"))) {
                    Main mf = new Main(res.getInt("id_user"), 2);
                    mf.setVisible(true);
                    this.dispose();
                    user = true;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (user == false) {
//            AlertFailed.setText("Maaf username dan password yang anda masukan salah! Mohon periksa kembali data diri anda");
            JOptionPane.showMessageDialog(null, "Maaf username dan password yang anda masukan salah!");
            JOptionPane.showMessageDialog(null, "Belum punya akun? Klik Daftar.");
            RegisterButton.setVisible(true);
            resetform();
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void FieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldUsernameActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        String username = FieldUsername.getText();
        String password = FieldPass.getText();
        
        if (!username.isEmpty() && !password.isEmpty())
        {
            String sql = "INSERT INTO user (username, password) VALUES ('"+username+"', '"+password+"')";
            db.updateQuery(sql);
            
            // Show Information
            System.out.println("Insert Success");
            JOptionPane.showMessageDialog(null, "Akun Berhasil Dibuat");
            
            resetform();
            RegisterButton.setVisible(false);
        }
        else
        {
            // Show Information
            System.out.println("Insert Failed");
            JOptionPane.showMessageDialog(null, "Harap isi semua data!");
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldPass;
    private javax.swing.JTextField FieldUsername;
    private javax.swing.JLabel LabelPass;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
